---
title: "Linear models - ForcePeaks 2025"
output: html_document
date: "2025-11-21"
---

## Load libraries
```{r setup, include=FALSE}

pacman::p_load(tidyverse, lmerTest, broom, modelsummary, patchwork, here, modelr, wesanderson, emmeans)


```


## Load data
```{r load_data, echo=FALSE}
# All conditions

data <- read_csv(here("data", "Df_2025.csv"), show_col_types = FALSE) %>%
	select(- '...1') %>%
	mutate(Effector = if_else(Effector == "D", "Finger", "Wrist"),
			Feedback = if_else(Subjs <= 26, "WithFbk", "NoFbk")) %>%
	rename(ISI = Period,
		   IPI = Peak_interval,
		   Participant = Subjs,
		   Asynchrony = Asyns_c)
data$ISI <- factor(data$ISI, levels=c('444','666'), ordered=TRUE)

datasummary_skim(data)


```


## Individual distributions of Peak_interval
```{r interpeak_interval_distributions, echo=FALSE}

plot_IPI_distributions <- data %>%
	ggplot(aes(x = IPI)) +
	geom_density(aes(color = Effector,
			   fill = Effector),
				 alpha=0.75) +
	facet_wrap(~Participant) +
	scale_color_manual(values = c("#0072B2", "#D55E00")) +
	theme_minimal() +
	theme(legend.position = "top",
		plot.background = element_rect(fill = "white", color = NA),
		strip.background = element_blank()) +
	labs(title = "With Feedback")
# uncomment to show plot
#plot_IPI_distributions

# remove subjects with inverted distributions:
# Peak_interval(Wrist) > Peak_interval(Finger)
# (results are not dependent on this---it's just cleaner)
participants_inverted_dists <- c(24,51,50)
removed_participants <- c(participants_inverted_dists)
data <- data %>%
	filter(! Participant %in% removed_participants)


```


## Out-of-phase data (subjects not following instructions)
```{r remove_out_of_phase, echo=FALSE}
# Detect and remove out-of-phase data

ISI_fraction_max = 0.25
outphase_fraction_max = 0.25


# condition for out-of=phase taps: large asynchrony close to half period
# (relative to mean asynchrony)
outphase_condition <- "Asynchrony + m_asyn > ISI_fraction_max*as.numeric(as.character(ISI)) | Asynchrony + m_asyn < -ISI_fraction_max*as.numeric(as.character(ISI))"

# plot out-of-phase subjects
plot_outphase <- data %>%
	group_by(Participant, Cond, Trial) %>%
	mutate(nTaps = n(),
		m_asyn = mean(Asynchrony)) %>%
	filter(eval(parse(text=outphase_condition))) %>%
	ggplot(aes(x = IPI, y = Asynchrony, color = factor(Participant))) +
	geom_point(alpha = 0.2) +
	geom_line(aes(group = interaction(Participant, Trial))) +
	facet_wrap(Effector~ISI) +
	theme_minimal() +
	theme_bw() +
	theme(legend.position = "top",
		strip.background = element_blank())
# uncomment to show plot
#plot_outphase

# detect out-of-phase trials
data_outphase <- data %>% 
	group_by(Participant, Cond, Trial) %>%
	mutate(nTaps = n(),
		m_asyn = mean(Asynchrony)) %>%
	# detect out-of-phase taps
	filter(eval(parse(text=outphase_condition))) %>%
	group_by(Participant, Cond, Trial, ISI) %>%
	summarise(count_outphase = n(),
			nTaps = first(nTaps),
			m_asyn = first(m_asyn),
			outphase_fraction = count_outphase/nTaps) %>%
	# detect trials with a large fraction of out-of-phase taps
	filter(outphase_fraction > outphase_fraction_max) %>%
	arrange(desc(count_outphase))
# remove out-of-phase trials
data_inphase <- data %>%
	anti_join(data_outphase, by = c("Participant", "Cond", "Trial"))


```


## Outliers
```{r outliers, echo=FALSE}

# detect and remove outliers (Tukey's fences)
data_inphase <- data_inphase %>%
	group_by(Participant, Cond) %>%
	mutate(Q1 = quantile(Asynchrony, 0.25),
			Q3 = quantile(Asynchrony, 0.75),
			lower_bound = Q1 - 1.5*(Q3-Q1),
			upper_bound = Q3 + 1.5*(Q3-Q1)) %>%
  filter(Asynchrony >= lower_bound & Asynchrony <= upper_bound) %>%
  select(-Q1, -Q3, -lower_bound, -upper_bound) %>%
  ungroup()

# detect and remove extremely short trials
data_inphase_participant <- data_inphase %>%
	group_by(Participant,Trial,Cond) %>%
	summarise(n_taps = n()) %>%
	filter(n_taps <= 2)
data_inphase <- data_inphase %>%
	anti_join(data_inphase_participant, by = c("Participant", "Cond", "Trial"))

# outlier summary
print(paste0('number of initial valid taps: ',nrow(data)))
print(paste0('number of valid trials flagged as antiphase: '
					,nrow(data_outphase)))
print(paste0('number of valid taps after antiphase and random outlier removal: '
					,nrow(data_inphase)))


```


## Full model
```{r full_model, echo=FALSE}

fsize <- 9
msize <- 1

# linear regression (random intercepts AND slopes!)
model_full <- lmer(data = data_inphase,
				Asynchrony ~ IPI*ISI*Feedback
						+ (1+IPI|Participant),
				control = lmerControl(optimizer ="Nelder_Mead"))

# add individual predictions
data_inphase <- data_inphase %>%
	add_predictions(model_full)

# compute averages for plotting theoretical trends
m_Asynchrony <- data_inphase %>%
	group_by(ISI, Feedback) %>%
	summarise(m_Asynchrony = mean(Asynchrony))

# plot
plot_fullmodel <- data_inphase %>%
	ggplot(aes(x = IPI, y = Asynchrony)) +
	geom_point(aes(color = Effector), alpha = 0.2, size=msize) +
	# optional: plot individual predictions
	# geom_line(aes(y = pred, group = Subjs), color="darkgray") +
	geom_smooth(aes(group = 1), method = "lm", color = "black", linewidth=0.5) +
	geom_abline(data = m_Asynchrony, aes(intercept = m_Asynchrony, slope = 0),
				linetype = "dashed", color = "black") +
	geom_abline(data = m_Asynchrony, aes(intercept = m_Asynchrony, slope = -1),
				linetype = "dashed", color = "black") +
	facet_grid(Feedback~ISI) +
	scale_color_manual(values = c("#0072B2", "#D55E00")) +
	theme_minimal(base_size=fsize) +
	labs(x="Interpeak interval (ms)", y="Asynchrony (ms)")
plot_fullmodel

ggsave("plot_full.pdf", plot=plot_fullmodel, width=8, height=4)
ggsave("plot_full.png", plot=plot_fullmodel, width=8, height=4, bg='white',dpi=150)



# show statistics
summary(model_full)
anova(model_full)
print("(nonsignificant effect of Peak_interval)")

model_full_emtrends <- emtrends(model_full, pairwise~ISI:Feedback,
								var="IPI",
								lmer.df = "satterthwaite",
								lmerTest.limit = 10000)
model_full_emtrends
print("(slopes are not significantly different from each other---With Feedback slopes are negative, though)")

# # check regression assumptions
# plot_checkmodel <- plot(performance::check_model(model_full, panel=FALSE))
# plot_checkmodel


```


